language: generic
jdk:
  - openjdk8

jobs:
  include:
    - stage: JvmTests
      script:
        - lein do clean, compile, check, eastwood
        - lein trampoline test

    - stage: JsTests
      script:
        - nvm install 10.10 && nvm use 10.10
        - lein trampoline cljsbuild test 

    - stage: Benchmark
      if: branch = master
      script:
        - lein trampoline test :benchmark

    - stage: Release
      if: tag IS present
      deploy:
        - provider: script
          script: lein deploy clojars
          skip_cleanup: true
          on:
            tags: true
