language: clojure
jdk:
  - openjdk8

jobs:
  include:
    - stage: Tests
      script:
        - lein do clean, compile, check, eastwood
        - lein trampoline test

    - stage: Benchmark
      if: branch = master
      script:
        - lein trampoline test :benchmark

    - stage: Release
      if: tag IS present
      deploy:
        - provider: script
          script: lein deploy clojars
          skip_cleanup: true
          on:
            tags: true
